name: Add issues/PRs to project
on:
  issues: { types: [opened, labeled] }
  pull_request: { types: [opened] }

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/users/Mic12321/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
